### PR TITLE
Support connection strings in the qix and rest services

### PR DESCRIPTION
**Pull request by seriousben**
### Status

```
* [x] Under development
* [ ] Waiting for code review
* [ ] Waiting for merge
```

### Information

```
* [ ] Contains breaking changes
* [ ] Contains new API(s)
* [ ] Contains documentation
* [X] Contains test
```

### TODO

```
* [ ] Documentation
```

### CODE REVIEW

**Comment by peol** [comment]
Hey, thanks for the contribution (and sorry for the delayed feedback)!

Please also update the documentation regarding the possibility that `cfg.session` can also be a string/URL.

The `Qix.configureDefaults()` call will still add defaults to `cfg.session` even though it's a string (fix validation).

**Comment by peol** [comment]
This PR needs rebasing (and see review comments above for additional updates).

**Comment by seriousben** [comment]
Yes, thanks. As soon as I have some time I will update this PR.

**Comment by peol** [comment]
Closing this for now. Feel free to send a new PR our way whenever you get a chance to revisit.

**Pull request closed without merging**
