### PR TITLE
Refactor response interceptors to prepare for request interceptors

### PR DESCRIPTION
**Pull request by peol**
WIP. No (nit-picky) reviews needed yet :)

Relates to #234 and #95.

This PR removes the (internal) `api.delta` flag, as well as splitting out the interceptor logic and making it static instead of instance-based.

It's undecided if I'll be delivering this PR first, and solving #234 second, or doing it in this branch considering how intertwined the logic is.

### CODE REVIEW

**Comment by marcusoffesson** [comment]
Looks good! 👌 
Looking forward to see the request interceptor implementation!

**Comment by stoffeastrom** [comment]
Looks promising 👍

**Comment by stoffeastrom** [comment]
While your at it. Why not refactor out [handleObjectReferenceResponse](https://github.com/qlik-oss/enigma.js/blob/request-interceptor/src/session.js#L143-L159)
[response interceptor](https://github.com/qlik-oss/enigma.js/blob/request-interceptor/src/session.js#L203-L206) into it's own file also :)?

**Comment by peol** [comment]
@stoffeastrom We moved that out of the interceptor chain for v2 due to making the interceptor concept public, we may move this into the chain again ( @marcusoffesson is looking into the reasons behind moving it at the moment).

**Pull request merged**
