### PR TITLE
refactor(session): use event constants

### PR DESCRIPTION
**Pull request by stoffeastrom**
### Status
```
[ ] Under development
[x] Waiting for code review
[x] Waiting for merge
```

### CODE REVIEW

**Comment by marcusoffesson** [comment]
Hi @stoffeastrom!

Thanks for your contribution!
So far, we've used constants mostly for magic numbers (e.g. `WebSocket` close reason) and not for (human readable) string literals.
We are a bit hesitant to this change as we do not feel that readability is greatly improved. With that said, we are willing to reconsider this position if the arguments are compelling. :) Can you elaborate a bit on benefits you see of having events defined as constants? Thanks!

**Comment by stoffeastrom** [comment]
Well, the `Session` has gotten a bit more events since last time I visited the code base and I didn't get a good overview over which events that was emitted (quite many 10+). With this you can instantly see which events that are defined at least. Regarding the readability I agree it's a bit more verbose.

**Comment by marcusoffesson** [comment]
I agree with you to some extent. Yes, there are quite a number of events being emitted, but they are described in detail [here](https://github.com/qlik-oss/enigma.js/blob/master/docs/api.md#session-api).
I'm sorry to say, but I'm not convinced that these constants provides more clarity (to be honest, I find them more confusing since it's a mix of both `Session` and `RPC` events). I hope you do not feel too discouraged if I close this PR?

**Comment by stoffeastrom** [comment]
Not at all :)

**Comment by stoffeastrom** [comment]
I don't agree regarding that it is more confusing with the "mixed" `Session` and `RPC` events since the `Session` is delegating some of the `RPC` events. Imho they definitively provide more clarity working in the `Session` class when developing. The linked document is good from a "user" perspective.

**Pull request closed without merging**
