### PR TITLE
Use Promise.reject instead of throw in the api response interceptor

### PR DESCRIPTION
**Pull request by T-Wizard**
This is to play nice with the error logging in the angular 1.x Promise implementation (used in the sense client)
(Most of the time we get this error it is not an actual error but just the client testing if an object exists)

Fixes #[issue number].

### Status
```
[ ] Under development
[x] Waiting for code review
[ ] Waiting for merge
```
### Information
```
[ ] Contains breaking changes
[ ] Contains new API(s)
[ ] Contains documentation
[ ] Contains test
```

### CODE REVIEW

**Comment by peol** [comment]
`session.Promise` is not part of our public API, I don't think we should use private APIs in our interceptors. It doesn't make sense to document `session.Promise` either (perhaps we should expose a `session.config` property instead if so).

Just so that I understand you correctly—is there an actual issue with us using `throw` or is that more of a nuisance that you get a log message from angular's `$q`?

**Comment by T-Wizard** [comment]
@peol: I would say it is on the border between a large nuisance or a small issue. The error is common enough that it make you pay less attention to console errors and more likely to miss real errors.
(Sometime I feels like you get spammed with Object not found errors)

Separate question:
How do I fix the "Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}" error in the  "Publish test coverage to coveralls.io" build step?
(I get the same error when I try to run it locally to)

**Comment by peol** [comment]
So I guess in your case it's caused by angular.js v1.5, and fixed in v1.6 because the behaviour was confusing: https://stackoverflow.com/a/42250798 (which also mentions the `$exceptionHandler` service which I believe you may configure/define to avoid logging these).

I'm still on the fence here, I'll investigate our options a bit further...

In regards to your question about coveralls, it looks like it's an issue with our configuration of Circle CI and sharing secrets (needs environment variable secret) to forked repo pull requests. It might be something @axelssonHakan has to fix on master :)

**Comment by peol** [comment]
@T-Wizard Sorry for the late reply, been away on conference.

We will soon land a fix on master for your Circle CI woes with publishing coverage. I'm looking into designing a way to expose the configuration through `session` or similar which may allow us to use the Promise constructor inside interceptors, stay tuned.

**Comment by peol** [comment]
@T-Wizard @marcusoffesson PTAL at the updates.

**Pull request merged**
